openapi: 3.0.0
info:
  title: STD23042 - TD1
  version: 1.0.0
servers:
  - url: https://localhost.std23042.com
paths:
  /groups:
    get:
      tags:
        - Groups
      summary: Get all groups
      operationId: getGroups
      parameters:
        - name: groupName
          in: query
          description: Filter groups by name
          required: false
          schema:
            type: string
        - name: groupYearFrom
          in: query
          description: Filter groups after this date
          required: false
          schema:
            type: string
            format: date
            example: 2023-01-01
        - name: groupYearTo
          in: query
          description: Filter groups before this date
          required: false
          schema:
            type: string
            format: date
            example: 2023-12-31
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/PageSize"
      responses:
        '200':
          description: List of all groups
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Group"
    post:
      tags:
        - Groups
      summary: Create a new group
      operationId: createGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CrupdateGroup"
      responses:
        '201':
          description: Group created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
    put:
      tags:
        - Groups
      summary: Update an existing group
      operationId: updateGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CrupdateGroup"
      responses:
        '200':
          description: Group updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
  /groups/{id}:
    delete:
      tags:
        - Groups
      summary: Delete a group
      operationId: deleteGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Group deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
  
  /groups/{groupId}/students/{studentId}:
    put:
      tags:
        - Groups 
      summary: Attach on student to one group  
      operationId: attachOneStudentToOneGroup 
      parameters:
        - name: groupId 
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: studentId 
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Attached one student to one group
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Group"
  /groups/students:
    put:
      tags:
        - Groups 
      summary: Attach students to groups  
      operationId: attachStudentsToGroups 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/UpdateStudentGroup"
      responses:
        '200':
          description: Attached students to groups 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UpdateStudentGroup"

  /students/page/{page}/pageSize/{pageSize}:
    get:
      tags:
        - Students
      summary: Get all Students
      operationId: getStudents
      parameters:
        - name: name 
          in: query
          description: Filter student by name
          required: false
          schema:
            type: string
        - $ref: "#/components/parameters/PathPage"
        - $ref: "#/components/parameters/PathPageSize"

      responses:
        '200':
          description: List of all students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Student"
    post:
      tags:
        - Students
      summary: Create a new student
      operationId: createStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
      responses:
        '201':
          description: Student created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Student"
    put:
      tags:
        - Students
      summary: Update an existing student
      operationId: updateStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
      responses:
        '200':
          description: Student updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Student"
  /students/{id}:
    delete:
      tags:
        - Students
      summary: Delete an student
      operationId: deleteStudent
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Student deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Student"
components:
  schemas:
    UpdateStudentGroup:
      type: object
      properties:
        bookId:
          type: string
          format: uuid
          example: J2
        studentId:
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
    CrupdateGroup:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        name:
          type: string
          example: J2
        year:
          type: string
          format: date
          example: 2023
        effective:
          type: integer
          example: 45
        promotion:
          $ref: "#/components/schemas/Promotion"
    Group:
      type: object
      allOf:
        - $ref: "#/components/schemas/CrupdateGroup"
      properties:
        students:
          type: array
          items:
            $ref: "#/components/schemas/Student"
    Promotion:
      type: string
      enum:
        - G
        - H
        - J
        - K
    Student:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 471eae60-abba-4732-b2a0-2e2b4d04cea1
        name:
          type: string
          example: Lucas Clavel
        birthdate:
          type: string
          format: date
          example: 09-10-03 
        reference:
          type: string
          example: STD23042
        group:
          type: string
          example: J2
        sex:
          $ref: '#/components/schemas/Sex'
    Sex:
      type: string
      enum:
        - M
        - F
  parameters:
    PathPage:
      name: page
      in: path 
      required: true 
      description: Page to retrieve
      schema:
        type: integer
        default: 1
    PathPageSize:
      name: pageSize
      in: path
      required: true 
      description: PageSize to retrieve for each page
      schema:
        type: integer
        default: 50 
    Page:
      name: page
      in: query
      required: false 
      description: Page to retrieve
      schema:
        type: integer
        default: 1
    PageSize:
      name: pageSize
      in: query
      required: false 
      description: PageSize to retrieve for each page
      schema:
        type: integer
        default: 50 