openapi: 3.0.0
info:
  title: STD23042 - TD1
  version: 1.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/HEIVANINAH/library/1.0.0
  - url: https://localhost.std23042.com
paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      operationId: getBooks
      parameters:
        - name: bookName
          in: query
          description: Filter books by name
          required: false
          schema:
            type: string
        - name: releaseDateFrom
          in: query
          description: Filter books released after this date
          required: false
          schema:
            type: string
            format: date
            example: 2023-01-01
        - name: releaseDateTo
          in: query
          description: Filter books released before this date
          required: false
          schema:
            type: string
            format: date
            example: 2023-12-31
        - $ref: "#/components/parameters/QueryPaginationPage"
        - $ref: "#/components/parameters/QueryPaginationPageSize"
      responses:
        200:
          $ref: "#/components/responses/ListOfBook200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
    post:
      tags:
        - Books
      summary: Create a new book
      operationId: createBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CrupdateBook"
      responses:
        200:
          $ref: "#/components/responses/Book200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
    put:
      tags:
        - Books
      summary: Update an existing book
      operationId: updateBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CrupdateBook"
      responses:
        200:
          $ref: "#/components/responses/Book200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /books/{bookId}/authors/{authorId}:
    put:
      tags:
        - Books
      summary: Link Book to Author
      operationId: linkBookToAuthor
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: authorId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          $ref: "#/components/responses/Book200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /books/authors:
    put:
      tags:
        - Books
      summary: Link list of Book to Authors
      operationId: linkListOfBookToAuthors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/UpdateBookAuthor"
      responses:
        200:
          $ref: "#/components/responses/ListOfUpdatedAuthorBook200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /books/{id}:
    delete:
      tags:
        - Books
      summary: Delete a book
      operationId: deleteBook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          $ref: "#/components/responses/Book200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /authors/page/{page}/pageSize/{pageSize}:
    get:
      tags:
        - Authors
      summary: Get all Authors
      operationId: getAuthors
      parameters:
      - name: name 
        in: query
        description: Filter authors by name
        required: false
        schema:
          type: string
      - $ref: "#/components/parameters/PathPaginationPage"
      - $ref: "#/components/parameters/PathPaginationPageSize"
      responses:
        200:
          $ref: "#/components/responses/ListOfAuthors200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
    post:
      tags:
        - Authors
      summary: Create a new author
      operationId: createAuthor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Author"
      responses:
        200:
          $ref: "#/components/responses/Author200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
    put:
      tags:
        - Authors
      summary: Update an existing author
      operationId: updateAuthor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Author"
      responses:
        200:
          $ref: "#/components/responses/Author200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
  /authors/{id}:
    delete:
      tags:
        - Authors
      summary: Delete an author
      operationId: deleteAuthor
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          $ref: "#/components/responses/Author200"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
components:
  schemas:
    UpdateBookAuthor:
      type: object
      properties:
        bookId:
          type: string
          format: uuid
          example: J2
        authorId:
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
    Book:
      type: object
      allOf:
        - $ref: "#/components/schemas/CrupdateBook"
      properties:
        author:
          $ref: "#/components/schemas/Author"
    CrupdateBook:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        bookName:
          type: string
          example: Larouse
        pageNumbers:
          type: number
          example: 50
        releaseDate:
          type: string
          format: date
          example: 1925-04-10 
        topic:
          $ref: "#/components/schemas/Topic"      
    Topic:
      type: string
      enum:
        - ROMANCE
        - COMEDY
        - OTHER
    Author:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 471eae60-abba-4732-b2a0-2e2b4d04cea1
        name:
          type: string
          example: Lucas Clavel
        sex:
          $ref: '#/components/schemas/Sex'
    Sex:
      type: string
      enum:
        - M
        - F
    ApiResponse:
      type: object
      properties:
        status:
          type: object
          properties:
            code:
              type: number
              example: 200
            message:
              type: string
              example: OK
        body:
            type: object
  responses:
    Author200:
      description: One Author 
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ApiResponse"
            properties:
              body: 
                $ref: "#/components/schemas/Author"
    ListOfAuthors200:
      description: List of Author 
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ApiResponse"
            properties:
              body: 
                type: array
                items:
                  $ref: "#/components/schemas/Author"
    Book200:
      description: One Book 
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ApiResponse"
            properties:
              body: 
                $ref: "#/components/schemas/Book"
    ListOfUpdatedAuthorBook200:
      description: List of updateAuthorBook
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ApiResponse"
            properties:
              body: 
                type: array
                items:
                  $ref: "#/components/schemas/UpdateBookAuthor"
    ListOfBook200:
      description: List of Books 
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ApiResponse"
            properties:
              body: 
                type: array
                items:
                  $ref: "#/components/schemas/Book"
    400:
      description: bad request
      content:
        application/json:
          schema:
            type: object
            allOf:
              - $ref: "#/components/schemas/ApiResponse"
            default:
              status:
                code: 400
                message: BAD REQUEST
              body:
                error: Incorrect request
    403:
      description: forbidden
      content:
        application/json:
          schema:
            type: object
            allOf:
              - $ref: "#/components/schemas/ApiResponse"
            default:
              status:
                code: 403
                message: FORBIDDEN
              body:
                error: access denied
    500:
      description: internal server erreur
      content:
        application/json:
          schema:
            type: object
            allOf:
              - $ref: "#/components/schemas/ApiResponse"
            default:
              status:
                code: 500
                message: INTERNAL SERVER ERREUR
              body:
                error: internal server erreur
  parameters:
    PathPaginationPage:
      name: page
      in: path 
      required: true 
      description: Page to retrieve
      schema:
        type: integer
        default: 1
    PathPaginationPageSize:
      name: pageSize
      in: path
      required: true 
      description: PageSize to retrieve for each page
      schema:
        type: integer
        default: 50 
    QueryPaginationPage:
      name: page
      in: query
      required: false 
      description: Page to retrieve
      schema:
        type: integer
        default: 1
    QueryPaginationPageSize:
      name: pageSize
      in: query
      required: false 
      description: PageSize to retrieve for each page
      schema:
        type: integer
        default: 50 